import os
from system.db_manager import DBManager

class PlaybookBuilder:
    def __init__(self, workspace_root):
        self.workspace_root = workspace_root
        self.playbooks_dir = os.path.join(workspace_root, "playbooks")
        os.makedirs(self.playbooks_dir, exist_ok=True)

    def generate_playbook(self, company_name):
        db = DBManager()
        conn = db.sqlite3.connect(db.db_path)
        cursor = conn.cursor()
        
        # Join companies and market_gaps
        query = """
            SELECT c.name, c.origin_country, c.description, c.growth_signal,
                   mg.viability_score, mg.adaptation_strategy, mg.execution_plan,
                   mg.risks, mg.final_verdict, mg.full_report
            FROM companies c
            JOIN market_gaps mg ON c.id = mg.company_id
            WHERE c.name LIKE ?
            ORDER BY mg.id DESC LIMIT 1
        """
        cursor.execute(query, (f"%{company_name}%",))
        row = cursor.fetchone()
        conn.close()

        if not row:
            print(f"No gap analysis found for {company_name}")
            return None

        # Unpack
        (name, origin, desc, growth, score, adapt, plan, risks, verdict, full) = row

        filename = f"{name.replace(' ', '_')}_Playbook.md"
        filepath = os.path.join(self.playbooks_dir, filename)

        template = f"""# 📄 Replication Playbook: {name}

## 🎯 Executive Summary
- **Origin**: {origin}
- **Concept**: {desc}
- **Growth Signal**: {growth}
- **Replication Score**: {score}/10

---

## 🌎 1. Market Opportunity & Adaptation
{adapt}

---

## 🛠️ 2. Step-by-Step Execution Plan
{plan}

---

## ⚠️ 3. Risks & Local Challenges
{risks}

---

## 🏁 4. Final Verdict
{verdict}

---

## 📝 Full Intelligence Report
```text
{full}
```

---
*Generated by Market Intelligence Engine (MIE)*
"""

        with open(filepath, "w") as f:
            f.write(template)
        
        print(f"[Playbook] Generated: {filepath}")
        return filepath

# Fix for DBManager import in script context
import sqlite3
class PlaybookBuilderFixed(PlaybookBuilder):
    def generate_playbook(self, company_name):
        db = DBManager()
        conn = sqlite3.connect(db.db_path)
        cursor = conn.cursor()
        # ... same logic as above ...
        query = """
            SELECT c.name, c.origin_country, c.description, c.growth_signal,
                   mg.viability_score, mg.adaptation_strategy, mg.execution_plan,
                   mg.risks, mg.final_verdict, mg.full_report
            FROM companies c
            JOIN market_gaps mg ON c.id = mg.company_id
            WHERE c.name LIKE ?
            ORDER BY mg.id DESC LIMIT 1
        """
        cursor.execute(query, (f"%{company_name}%",))
        row = cursor.fetchone()
        conn.close()

        if not row:
            print(f"No gap analysis found for {company_name}")
            return None

        (name, origin, desc, growth, score, adapt, plan, risks, verdict, full) = row
        filename = f"{name.strip().replace(' ', '_')}_Playbook.md"
        filepath = os.path.join(self.playbooks_dir, filename)

        template = f"""# 📄 Replication Playbook: {name.strip()}

## 🎯 Executive Summary
- **Origin**: {origin.strip()}
- **Concept**: {desc.strip()}
- **Growth Signal**: {growth.strip()}
- **Replication Score**: {score}/10

---

## 🌎 1. Market Opportunity & Adaptation
{adapt.strip()}

---

## 🛠️ 2. Step-by-Step Execution Plan
{plan.strip()}

---

## ⚠️ 3. Risks & Local Challenges
{risks.strip()}

---

## 🏁 4. Final Verdict
{verdict.strip()}

---

## 📝 Full Intelligence Report
```text
{full.strip()}
```

---
*Generated by Market Intelligence Engine (MIE)*
"""
        with open(filepath, "w") as f:
            f.write(template)
        
        return filepath
