import os
import sqlite3
from system.db_manager import DBManager

class PlaybookBuilder:
    def __init__(self, workspace_root):
        self.workspace_root = workspace_root
        self.playbooks_dir = os.path.join(workspace_root, "playbooks")
        os.makedirs(self.playbooks_dir, exist_ok=True)

    def generate_playbook(self, company_name):
        db = DBManager()
        conn = sqlite3.connect(db.db_path)
        cursor = conn.cursor()

        query = """
            SELECT c.name, c.origin_country, c.description, c.growth_signal,
                   mg.viability_score, mg.adaptation_strategy, mg.execution_plan,
                   mg.risks, mg.final_verdict, mg.full_report
            FROM companies c
            JOIN market_gaps mg ON c.id = mg.company_id
            WHERE c.name LIKE ?
            ORDER BY mg.id DESC LIMIT 1
        """
        cursor.execute(query, (f"%{company_name}%",))
        row = cursor.fetchone()
        conn.close()

        if not row:
            print(f"No gap analysis found for {company_name}")
            return None

        (name, origin, desc, growth, score, adapt, plan, risks, verdict, full) = row

        filename = f"{name.strip().replace(' ', '_')}_Playbook.md"
        filepath = os.path.join(self.playbooks_dir, filename)

        template = f"""# 📄 Replication Playbook: {name.strip()}

## 🎯 Executive Summary
- **Origin**: {(origin or '').strip()}
- **Concept**: {(desc or '').strip()}
- **Growth Signal**: {(growth or '').strip()}
- **Replication Score**: {score}/10

---

## 🌎 1. Market Opportunity & Adaptation
{(adapt or '').strip()}

---

## 🛠️ 2. Step-by-Step Execution Plan
{(plan or '').strip()}

---

## ⚠️ 3. Risks & Local Challenges
{(risks or '').strip()}

---

## 🏁 4. Final Verdict
{(verdict or '').strip()}

---

## 📝 Full Intelligence Report
```text
{(full or '').strip()}
```

---
*Generated by Market Intelligence Engine (MIE)*
"""

        with open(filepath, "w") as f:
            f.write(template)

        print(f"[Playbook] Generated: {filepath}")
        return filepath
